# Basic prefix for LessTalk plugin
prefix: "&7[&bLessTalk&7]"

# Only placeholder available as of now is %player_displayname%
# More will be added in the future.
staff_chat_format: "&7[&cStaff Chat&7] &b%player_displayname% &7: "


# If you have this disabled, players can rack up as many warns as they want!
warn_punish: true
# How many warns can a player have before the plugin takes action
warn_amount: 10
# If you have your punishment set as "TEMPBAN" you can decide how long this is in effect.
# D = Days
# M = Months
ban_duration: "7d"
punishment: "BAN"
punishment_reason: "You have been banned for being naughty!"

# How long should players wait to send messages?
# This is represented in seconds.
time_between_messages: 2

# Here you can enable / disable different parts of the Plugin
# If one of the commands / or plugin function(s) are conflicting with another plugin, you have the option to disable that command / module.
# True is enabled. False is disabled.
module_toggle:
  staff_chat: true
  mute_players: true
  slow_mode: true
  chat_lock: true
  clear_chat: true
  duplicate_message_check: true
  filter_chat: true
  warn_player: true


# Filter words on your server!
filtered_chat:
  - "butthead"
  - "poopybutt"